---
title: "PHS Summer Prep"
output:
  learnr::tutorial:
    theme: paper
    version: 1.1
    css: www/style.css
    js: www/keep_alive.js
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(fig.align = "center",
                      cache = TRUE)
tutorial_options(exercise.timelimit = 60)
options(digits = 5, scipen = 999)

pmf_func <- function(x, fx){
  par(mgp = c(3, 1, 0), mar = c(4, 4, 1, 1))
  plot(x, fx, type = "h", col = "blue", xaxt = "n", main = "pmf", ylab = "", xlab = "")
  abline(h = 0)
  points(x, fx, col = "blue", pch = 19)
  axis(1, xaxp = c(min(x), max(x), length(x) - 1))
  title(ylab="f(x)", line = 2, xlab = "x")
}

cdf_func <- function(x, fx){
  par(mgp = c(3, 1, 0), mar = c(4, 4, 1, 1))
  cdf <- c(0, cumsum(fx))
  plot(stepfun(x, cdf),xlab = "",ylab = "", verticals = FALSE, do.points = TRUE, pch = 16, main = "cdf", col = "red")
  points(x, cdf[-length(cdf)], col = "red")
  title(ylab="F(x)", line = 2, xlab = "x")
}

```
```{r ralive, context="render", echo=FALSE}
textOutput("keep_alive")
```
```{r salive, context="server", echo=FALSE}
output$keep_alive <- renderText({
  req(input$alive_count)
  input$alive_count
})
```
```{r child = 'why.Rmd'}
```

```{r child = 'intro.Rmd'}
```

```{r child = 'vectors.Rmd'}
```

```{r child = 'rules.Rmd'}
```

```{r child = 'discrete.Rmd'}
```

```{r child = 'cdfs.Rmd'}
```

```{r child = 'marginal.Rmd'}
```

```{r child = 'total.Rmd'}
```

```{r child = 'calculus.Rmd'}
```

```{r child = 'pdfs.Rmd'}
```

```{r child = 'expectations.Rmd'}
```

```{r child = 'matrix.Rmd'}
```

```{r child = 'models.Rmd'}
```

```{r child = 'stats.Rmd'}
```

```{r child = 'glossary.Rmd'}
```

```{r child = 'resources.Rmd'}
```
